import './globals.css';
import type { Metadata } from 'next';
import Navbar from '@/components/navbar/navbar';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export const dynamic = 'force-dynamic';

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html className="!scroll-smooth">
      <body className="flex flex-col h-screen">
        <Navbar />
        {children}
      </body>
    </html>
  );
}
