import './globals.css';
import type { Metadata } from 'next';
import Navbar from '@/components/navbar/navbar';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html className="!scroll-smooth">
      <body
        className="flex flex-col h-screen m-0 p-0"
        style={{
          backgroundColor: '#081b29',
        }}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
